services:
  # ==================================================
  # PostgreSQL SOURCE
  # ==================================================
  postgres:
    image: postgres:15
    container_name: postgres_reviews
    restart: unless-stopped
    env_file:
      - ./config/.env
      - ./config/secrets.env
    environment:
      POSTGRES_USER: ${POSTGRES_SOURCE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ==================================================
  # MongoDB (BRONZE)
  # ==================================================
  mongo:
    image: mongo:6
    container_name: mongo_reviews
    restart: unless-stopped
    env_file:
      - ./config/.env
      - ./config/secrets.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_reviews
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - ./config/.env
      - ./config/secrets.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo

  # ==================================================
  # AIRFLOW METADATA DATABASE
  # ==================================================
  airflow-postgres:
    image: postgres:15
    container_name: airflow_postgres
    env_file:
      - ./config/.env
      - ./config/secrets.env
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==================================================
  # AIRFLOW INIT
  # ==================================================
  airflow-init:
    build: .
    image: amazonreviews-airflow:2.9.3-python3.10
    container_name: airflow_init
    depends_on:
      airflow-postgres:
        condition: service_healthy
    env_file:
      - ./config/.env
      - ./config/secrets.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    entrypoint: /bin/bash
    command:
    - -c
    - |
      airflow db init
      airflow users create \
        --username "${AIRFLOW_ADMIN_USER}" \
        --password "${AIRFLOW_ADMIN_PASSWORD}" \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com

  # ==================================================
  # AIRFLOW WEBSERVER
  # ==================================================
  airflow-webserver:
    image: amazonreviews-airflow:2.9.3-python3.10
    container_name: airflow_webserver
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - ./config/.env
      - ./config/secrets.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/project
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/project/src
      - ./logs:/opt/airflow/logs
      - ./shared:/shared
    ports:
      - "8080:8080"
    command: webserver

  # ==================================================
  # AIRFLOW SCHEDULER
  # ==================================================
  airflow-scheduler:
    image: amazonreviews-airflow:2.9.3-python3.10
    container_name: airflow_scheduler
    depends_on:
      airflow-webserver:
        condition: service_started
    env_file:
      - ./config/.env
      - ./config/secrets.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      PYTHONPATH: /opt/airflow/project
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/project/src
      - ./logs:/opt/airflow/logs
      - ./shared:/shared
    command: scheduler

volumes:
  postgres_data:
  mongo_data:
  airflow_db:
